### ISSUE TITLE
Need ability to call function when flickThreshold is reached.

### ISSUE THREAD

**Issue by brettshumaker** [shiminshen/react-swipe-row#1]
Looks like you're early on in the development of this package, and I'm sure that this is something you'll add in but just wanted to mention it. 🙂 

I'd like to use this on a project currently starting development but I'll need to be able to call a function if the user passes the `flickThreshold` while swiping. Looked around but I don't see a way to access `state.move` during `onTouchMove`. Please let me know if I'm wrong. 👍

**Comment by shiminshen** [comment]
Thanks for mentioning this problem. I did not think about the scenario. I will pass the related ```state``` to the related callback function in the next version.

**Comment by shiminshen** [comment]
This problem is fixed in ```0.1.0```. You can access ```state.move``` by the second parameter of ```onTouchMove```.
